version: '3.8'
services:
  sshd:
    image: linuxserver/openssh-server
    container_name: mqi-test-sshd
    ports:
      - "2222:2222"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER_NAME=testuser
      - USER_PASSWORD=testpass
      - PASSWORD_ACCESS=true
    volumes:
      - ./remote_workspace:/home/testuser/workspace
